# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0F1011)
$foreground = rgb(D6E7E8)
$color0 = rgb(383939)
$color1 = rgb(080D0E)
$color2 = rgb(0B1011)
$color3 = rgb(314C50)
$color4 = rgb(3B5A5E)
$color5 = rgb(678C8E)
$color6 = rgb(678C8E)
$color7 = rgb(BCD5D6)
$color8 = rgb(839595)
$color9 = rgb(0B1113)
$color10 = rgb(0E1517)
$color11 = rgb(42656A)
$color12 = rgb(4E787D)
$color13 = rgb(89BBBD)
$color14 = rgb(89BBBD)
$color15 = rgb(BCD5D6)
