# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ABACAF
background         #111214
cursor             #5C5F64

active_tab_foreground     #111214
active_tab_background     #ABACAF
inactive_tab_foreground   #ABACAF
inactive_tab_background   #111214

active_border_color   #ABACAF
inactive_border_color #111214
bell_border_color     #0A0D13

color0      #393A3C
color1		#0A0D13
color2		#0A0D13
color3		#0A0D13
color4		#0A0D13
color5		#0B0D14
color6		#0B0D14
color7		#7E8084
color8		#585A5C
color9		#0E121A
color10		#0E121A
color11		#0E121A
color12		#0E121A
color13		#0E121A
color14		#0E121A
color15		#7E8084
