# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D6E7E8
background         #0F1011
cursor             #727E7F

active_tab_foreground     #0F1011
active_tab_background     #D6E7E8
inactive_tab_foreground   #D6E7E8
inactive_tab_background   #0F1011

active_border_color   #D6E7E8
inactive_border_color #0F1011
bell_border_color     #080D0E

color0      #383939
color1		#080D0E
color2		#0B1011
color3		#314C50
color4		#3B5A5E
color5		#678C8E
color6		#678C8E
color7		#BCD5D6
color8		#839595
color9		#0B1113
color10		#0E1517
color11		#42656A
color12		#4E787D
color13		#89BBBD
color14		#89BBBD
color15		#BCD5D6
